---
    - name: Define servers
      include_tasks: create-server.yaml
      #since the var is dict, convert it into list for looping
      loop: "{{ osp_servers|dict2items}}"
      loop_control:
        loop_var: _server
        label: "{{ _server.key }}"